name: Matrix deploy
run-name: ${{ github.actor }}
on:
  push:
    branches: [ main ]
jobs:
  Build-matrix:
    runs-on: ubuntu-latest
    environment: deploy_staging
    env:
      DOMAIN_NAME: ${{ secrets.DOMAIN_NAME }}
      REMOTE_SERVER_HOST: ${{ secrets.REMOTE_SERVER_HOST }}
      REMOTE_SERVER_USER: ${{ secrets.REMOTE_SERVER_USER }}
      REMOTE_SERVER_PASSWORD: ${{ secrets.REMOTE_SERVER_PASSWORD }}
      MATRIX_DOMAIN: ${{ secrets.MATRIX_DOMAIN }}
      MATRIX_HOMESERVER_IMPLEMENTATION: ${{ secrets.MATRIX_HOMESERVER_IMPLEMENTATION }}
      MATRIX_HOMESERVER_GENERIC_SECRET_KEY: ${{ secrets.MATRIX_HOMESERVER_GENERIC_SECRET_KEY }}
      MATRIX_SSL_LETS_ENCRYPT_SUPPORT_EMAIL: ${{ secrets.MATRIX_SSL_LETS_ENCRYPT_SUPPORT_EMAIL }}
      MATRIX_POSTGRES_ENABLED: ${{ secrets.MATRIX_POSTGRES_ENABLED }}
      MATRIX_SYNAPSE_DATABASE_HOST: ${{ secrets.MATRIX_SYNAPSE_DATABASE_HOST }}
      MATRIX_SYNAPSE_DATABASE_USER: ${{ secrets.MATRIX_SYNAPSE_DATABASE_USER }}
      MATRIX_SYNAPSE_DATABASE_PASSWORD: ${{ secrets.MATRIX_SYNAPSE_DATABASE_PASSWORD }}
      MATRIX_SYNAPSE_DATABASE_DATABASE: ${{ secrets.MATRIX_SYNAPSE_DATABASE_DATABASE }}
      MATRIX_NGINX_PROXY_BASE_DOMAIN_SERVING_ENABLED: ${{ secrets.MATRIX_NGINX_PROXY_BASE_DOMAIN_SERVING_ENABLED }}
      MATRIX_SYNAPSE_ADMIN_ENABLED: ${{ secrets.MATRIX_SYNAPSE_ADMIN_ENABLED }}
      MATRIX_SYNAPSE_EXT_PASSWORD_PROVIDER_SHARED_SECRET_AUTH_ENABLED: ${{ secrets.MATRIX_SYNAPSE_EXT_PASSWORD_PROVIDER_SHARED_SECRET_AUTH_ENABLED }}
      MATRIX_SYNAPSE_EXT_PASSWORD_PROVIDER_SHARED_SECRET_AUTH_SHARED_SECRET: ${{ secrets.MATRIX_SYNAPSE_EXT_PASSWORD_PROVIDER_SHARED_SECRET_AUTH_SHARED_SECRET }}
      MATRIX_MAUTRIX_WHATSAPP_ENABLED: ${{ secrets.MATRIX_MAUTRIX_WHATSAPP_ENABLED }}
      MATRIX_MAUTRIX_WHATSAPP_CONTAINER_IMAGE_SELF_BUILD: ${{ secrets.MATRIX_MAUTRIX_WHATSAPP_CONTAINER_IMAGE_SELF_BUILD }}
      MATRIX_MAUTRIX_WHATSAPP_CONTAINER_IMAGE_SELF_BUILD_REPO: ${{ secrets.MATRIX_MAUTRIX_WHATSAPP_CONTAINER_IMAGE_SELF_BUILD_REPO }}
      MATRIX_MAUTRIX_WHATSAPP_CONTAINER_IMAGE_SELF_BUILD_BRANCH: ${{ secrets.MATRIX_MAUTRIX_WHATSAPP_CONTAINER_IMAGE_SELF_BUILD_BRANCH }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build container
        run: |
          docker-compose up --build
